# -*- coding: utf-8 -*-
"""
核心模块：光学成像、傅里叶变换、误差评估
"""

from core.imaging import (
    OpticalSystem,
    PartialCoherentImaging,
    simulate_wafer_image,
    IlluminationType,
    generate_source,
    compute_tcc_kernel_2d,
    compute_tcc_full,
    socs_decomposition,
    ProcessCondition,
    ProcessWindow,
    MultiProcessSimulationResult,
    simulate_multi_process,
    create_focus_dose_window,
    create_full_process_window,
    ResistType,
    ResistThresholdMode,
    ResistModel,
    apply_resist_model,
    downsample_mask,
    upsample_mask,
    build_pyramid_scales,
    split_tiles,
    merge_tiles_with_blend
)
from core.fft import (
    fft2d, ifft2d, fft1d, ifft1d, frequency_filter, phase_modulation,
    WindowType, hann_window_2d, hamming_window_2d, tukey_window_2d,
    create_window, apply_zero_padding, remove_padding,
    apply_window_and_padding, crop_to_original
)
from core.metrics import mse, mae, ssim, normalized_correlation, batch_evaluate
from core.metrics import (
    HistoryEvaluationRow,
    batch_evaluate_history,
    export_evaluation_csv,
    compute_pareto_front,
    evaluate_and_export_pareto,
    total_variation,
    total_variation_isotropic,
    manhattan_distance_penalty,
)

__all__ = [
    'OpticalSystem',
    'PartialCoherentImaging',
    'simulate_wafer_image',
    'IlluminationType',
    'generate_source',
    'compute_tcc_kernel_2d',
    'compute_tcc_full',
    'socs_decomposition',
    'ProcessCondition',
    'ProcessWindow',
    'MultiProcessSimulationResult',
    'simulate_multi_process',
    'create_focus_dose_window',
    'create_full_process_window',
    'ResistType',
    'ResistThresholdMode',
    'ResistModel',
    'apply_resist_model',
    'downsample_mask',
    'upsample_mask',
    'build_pyramid_scales',
    'split_tiles',
    'merge_tiles_with_blend',
    'fft2d',
    'ifft2d',
    'fft1d',
    'ifft1d',
    'frequency_filter',
    'phase_modulation',
    'WindowType',
    'hann_window_2d',
    'hamming_window_2d',
    'tukey_window_2d',
    'create_window',
    'apply_zero_padding',
    'remove_padding',
    'apply_window_and_padding',
    'crop_to_original',
    'mse',
    'mae',
    'ssim',
    'normalized_correlation',
    'batch_evaluate',
    'HistoryEvaluationRow',
    'batch_evaluate_history',
    'export_evaluation_csv',
    'compute_pareto_front',
    'evaluate_and_export_pareto',
    'total_variation',
    'total_variation_isotropic',
    'manhattan_distance_penalty',
]
